### PR TITLE
Added items to queue in constructor.

### PR DESCRIPTION
**Pull request by darenju**
Added the ability to add images directly in the constructor.

### CODE REVIEW

**Comment by KittyGiraudel** [comment]
While I can see the benefit, I am not a big fan of shortcutting steps. It makes the whole thing harder to use (because more complex), as far as I can tell.

**Comment by darenju** [comment]
I agree, but since this tool has only one single function, why not just add the items directly? Then queue prospective images in the future that need to be loaded?

**Comment by KittyGiraudel** [comment]
Might make sense. I am actually thinking of getting rid of `.queue()` and `.preload()` all together, and only provide a single function (well, 2; one for parallel, one for sequence).

**Comment by darenju** [comment]
This can be a good idea, IMO. Load the constructor with items, then use `.parallel()` and `.sequence()`. Sounds good.

Or just `.parallel(items)`… Needs some thinking here.

**Comment by KittyGiraudel** [comment]
Wouldn't be a constructor anymore. See: http://codepen.io/HugoGiraudel/pen/84c2691981779450d14c9eb4b62b2a2f. Actually I like your idea.

**Comment by darenju** [comment]
The second one of `.parrallel(items)`? Actually I like this idea more than the constructor thing to be honest. So something like that: `(new ImagePreloader()).parrallel(items)`?

**Comment by KittyGiraudel** [comment]
Possible solutions:

``` javascript
preloadParallel(items);
```

``` javascript
var ip = new ImagePreloader(items);

ip.parallel();
```

``` javascript
var ip = new ImagePreloader();

items.parallel(items);
```

**Comment by darenju** [comment]
I like the two ones with `ImagePreloader`. The last one is like what I suggested just before. Makes more sense to me than the second suggestion.

**Pull request merged**
